# types : Vascel, Speed, Life, Aither, Armor, Aspis, FireResistance, Force, Ground, NoDamageFall, Pur, Vigueur, Watter

effects:
  Vascel:
    cooldown: 60 # in seconds
    message: "You have been teleported !"
    sound: "ENTITY_ENDERMAN_TELEPORT"
    max_distance: 100

craft:
  Vascel:
    runeName: "Vascel"
    slot1: "NETHER_STAR"
    slot2: "ENDER_PEARL"
    slot3: "NETHER_STAR"
    slot4: "ENDER_PEARL"
    slot5: "NETHER_STAR"
    slot6: "ENDER_PEARL"
    slot7: "NETHER_STAR"
    slot8: "ENDER_PEARL"
    slot9: "NETHER_STAR"
  Speed:
    runeName: "Speed1"
    slot1: "SUGAR"
    slot2: "FEATHER"
    slot3: "SUGAR"
    slot4: "FEATHER"
    slot5: "SUGAR"
    slot6: "FEATHER"
    slot7: "SUGAR"
    slot8: "FEATHER"
    slot9: "SUGAR"
  Life:
    runeName: "Life1"
    slot1: "GOLDEN_APPLE"
    slot2: "GOLDEN_CARROT"
    slot3: "GOLDEN_APPLE"
    slot4: "GOLDEN_CARROT"
    slot5: "GOLDEN_APPLE"
    slot6: "GOLDEN_CARROT"
    slot7: "GOLDEN_APPLE"
    slot8: "GOLDEN_CARROT"
    slot9: "GOLDEN_APPLE"
  Aither:
    runeName: "Aither"
    slot1: "PHANTOM_MEMBRANE"
    slot2: "FEATHER"
    slot3: "PHANTOM_MEMBRANE"
    slot4: "FEATHER"
    slot5: "PHANTOM_MEMBRANE"
    slot6: "FEATHER"
    slot7: "PHANTOM_MEMBRANE"
    slot8: "FEATHER"
    slot9: "PHANTOM_MEMBRANE"
  Armor:
    runeName: "Armor1"
    slot1: "IRON_INGOT"
    slot2: "DIAMOND"
    slot3: "IRON_INGOT"
    slot4: "DIAMOND"
    slot5: "IRON_INGOT"
    slot6: "DIAMOND"
    slot7: "IRON_INGOT"
    slot8: "DIAMOND"
    slot9: "IRON_INGOT"
  Aspis:
    runeName: "Aspis"
    slot1: "SHIELD"
    slot2: "IRON_INGOT"
    slot3: "SHIELD"
    slot4: "IRON_INGOT"
    slot5: "SHIELD"
    slot6: "IRON_INGOT"
    slot7: "SHIELD"
    slot8: "IRON_INGOT"
    slot9: "SHIELD"
  FireResistance:
    runeName: "FireResistance"
    slot1: "MAGMA_CREAM"
    slot2: "BLAZE_POWDER"
    slot3: "MAGMA_CREAM"
    slot4: "BLAZE_POWDER"
    slot5: "MAGMA_CREAM"
    slot6: "BLAZE_POWDER"
    slot7: "MAGMA_CREAM"
    slot8: "BLAZE_POWDER"
    slot9: "MAGMA_CREAM"
  Force:
    runeName: "Force1"
    slot1: "BLAZE_ROD"
    slot2: "NETHER_WART"
    slot3: "BLAZE_ROD"
    slot4: "NETHER_WART"
    slot5: "BLAZE_ROD"
    slot6: "NETHER_WART"
    slot7: "BLAZE_ROD"
    slot8: "NETHER_WART"
    slot9: "BLAZE_ROD"
  Ground:
    runeName: "Ground"
    slot1: "DIRT"
    slot2: "GRASS_BLOCK"
    slot3: "DIRT"
    slot4: "GRASS_BLOCK"
    slot5: "DIRT"
    slot6: "GRASS_BLOCK"
    slot7: "DIRT"
    slot8: "GRASS_BLOCK"
    slot9: "DIRT"
  NoDamageFall:
    runeName: "NoDamageFall"
    slot1: "FEATHER"
    slot2: "SLIME_BALL"
    slot3: "FEATHER"
    slot4: "SLIME_BALL"
    slot5: "FEATHER"
    slot6: "SLIME_BALL"
    slot7: "FEATHER"
    slot8: "SLIME_BALL"
    slot9: "FEATHER"
  Pur:
    runeName: "Pur"
    slot1: "QUARTZ"
    slot2: "GLOWSTONE_DUST"
    slot3: "QUARTZ"
    slot4: "GLOWSTONE_DUST"
    slot5: "QUARTZ"
    slot6: "GLOWSTONE_DUST"
    slot7: "QUARTZ"
    slot8: "GLOWSTONE_DUST"
    slot9: "QUARTZ"
  Vigueur:
    runeName: "Vigueur1"
    slot1: "GOLDEN_CARROT"
    slot2: "GOLDEN_APPLE"
    slot3: "GOLDEN_CARROT"
    slot4: "GOLDEN_APPLE"
    slot5: "GOLDEN_CARROT"
    slot6: "GOLDEN_APPLE"
    slot7: "GOLDEN_CARROT"
    slot8: "GOLDEN_APPLE"
    slot9: "GOLDEN_CARROT"
  Watter:
    runeName: "Eau"
    slot1: "WATER_BUCKET"
    slot2: "PRISMARINE_SHARD"
    slot3: "WATER_BUCKET"
    slot4: "PRISMARINE_SHARD"
    slot5: "WATER_BUCKET"
    slot6: "PRISMARINE_SHARD"
    slot7: "WATER_BUCKET"
    slot8: "PRISMARINE_SHARD"
    slot9: "WATER_BUCKET"


runes:
  vitesse1:
    name: "Vitesse"
    allowed_items:
      - "LEATHER_BOOTS"
      - "CHAINMAIL_BOOTS"
      - "IRON_BOOTS"
      - "GOLDEN_BOOTS"
      - "DIAMOND_BOOTS"
      - "NETHERITE_BOOTS"
    level: 1
    is_upgradeable: true
    effects:
      - type: "Speed"
        onHoldItem: false
        onEquip: true
        onPlayerInteract: false
  vitesse2:
    name: "Vitesse"
    allowed_items:
      - "LEATHER_BOOTS"
      - "CHAINMAIL_BOOTS"
      - "IRON_BOOTS"
      - "GOLDEN_BOOTS"
      - "DIAMOND_BOOTS"
      - "NETHERITE_BOOTS"
    level: 2
    is_upgradeable: true
    effects:
      - type: "Speed"
        onHoldItem: false
        onEquip: true
        onPlayerInteract: false
  vitesse3:
    name: "Vitesse"
    allowed_items:
      - "LEATHER_BOOTS"
      - "CHAINMAIL_BOOTS"
      - "IRON_BOOTS"
      - "GOLDEN_BOOTS"
      - "DIAMOND_BOOTS"
      - "NETHERITE_BOOTS"
    level: 3
    is_upgradeable: true
    effects:
      - type: "Speed"
        onHoldItem: false
        onEquip: true
        onPlayerInteract: false
  vitesse4:
    name: "Vitesse"
    allowed_items:
      - "LEATHER_BOOTS"
      - "CHAINMAIL_BOOTS"
      - "IRON_BOOTS"
      - "GOLDEN_BOOTS"
      - "DIAMOND_BOOTS"
      - "NETHERITE_BOOTS"
    level: 4
    is_upgradeable: true
    effects:
      - type: "Speed"
        onHoldItem: false
        onEquip: true
        onPlayerInteract: false
  vitesse5:
    name: "Vitesse"
    allowed_items:
      - "LEATHER_BOOTS"
      - "CHAINMAIL_BOOTS"
      - "IRON_BOOTS"
      - "GOLDEN_BOOTS"
      - "DIAMOND_BOOTS"
      - "NETHERITE_BOOTS"
    level: 5
    is_upgradeable: false
    effects:
      - type: "Speed"
        onHoldItem: false
        onEquip: true
        onPlayerInteract: false
