effects:
  Vascel:
    cooldown: 60 # in seconds
    message: "You have been teleported !"
    sound: "ENTITY_ENDERMAN_TELEPORT"
    max_distance: 100

runes:
  vitesse1:
    name: "Vitesse"
    allowed_items:
      - "LEATHER_BOOTS"
      - "CHAINMAIL_BOOTS"
      - "IRON_BOOTS"
      - "GOLDEN_BOOTS"
      - "DIAMOND_BOOTS"
      - "NETHERITE_BOOTS"
    level: 1
    is_upgradeable: true
    effects:
      - type: "Speed"
        onHoldItem: false
        onEquip: true
        onPlayerInteract: false
  vitesse2:
    name: "Vitesse"
    allowed_items:
      - "LEATHER_BOOTS"
      - "CHAINMAIL_BOOTS"
      - "IRON_BOOTS"
      - "GOLDEN_BOOTS"
      - "DIAMOND_BOOTS"
      - "NETHERITE_BOOTS"
    level: 2
    is_upgradeable: true
    effects:
      - type: "Speed"
        onHoldItem: false
        onEquip: true
        onPlayerInteract: false
  vitesse3:
    name: "Vitesse"
    allowed_items:
      - "LEATHER_BOOTS"
      - "CHAINMAIL_BOOTS"
      - "IRON_BOOTS"
      - "GOLDEN_BOOTS"
      - "DIAMOND_BOOTS"
      - "NETHERITE_BOOTS"
    level: 3
    is_upgradeable: true
    effects:
      - type: "Speed"
        onHoldItem: false
        onEquip: true
        onPlayerInteract: false
  vitesse4:
    name: "Vitesse"
    allowed_items:
      - "LEATHER_BOOTS"
      - "CHAINMAIL_BOOTS"
      - "IRON_BOOTS"
      - "GOLDEN_BOOTS"
      - "DIAMOND_BOOTS"
      - "NETHERITE_BOOTS"
    level: 4
    is_upgradeable: true
    effects:
      - type: "Speed"
        onHoldItem: false
        onEquip: true
        onPlayerInteract: false
  vitesse5:
    name: "Vitesse"
    allowed_items:
      - "LEATHER_BOOTS"
      - "CHAINMAIL_BOOTS"
      - "IRON_BOOTS"
      - "GOLDEN_BOOTS"
      - "DIAMOND_BOOTS"
      - "NETHERITE_BOOTS"
    level: 5
    is_upgradeable: false
    effects:
      - type: "Speed"
        onHoldItem: false
        onEquip: true
        onPlayerInteract: false
